### ISSUE TITLE
Erro _ssl  na api

### ISSUE THREAD

**Issue by cm-ms** [Felipeecp/api-rendimento#4]
Erro _ssl.c1129 na api quando vai consultar as tabelas.
prováveis soluções: https://stackoverflow.com/questions/38015537/python-requests-exceptions-sslerror-dh-key-too-small

**Comment by cm-ms** [comment]
@Felipeecp  @radoslz 
Vamos deixar com csv mesmo?

**Comment by radoslz** [comment]
se desse de programar pra ele fazer só uma requisição e salve-se, tipo no próprio app.py

**Comment by Felipeengc** [comment]
o problema é só que o heroku quebra sempre que tenta pegar os dados do site do tesouro, tentei pegar do download que tem na pagina mas da erro unicode no csv, enfim o caos

**Comment by cm-ms** [comment]
da de fazer isso, @radoslz 
Mas acho que o problema é na requisição mesmo
